import type { Garment, Profile, Order } from '../types';

export const DEMO_SELLER: Profile = {
  id: 'seller1',
  email: 'vendedor@revibe.co',
  full_name: 'Valentina Morales',
  city: 'Medellín',
  role: 'seller',
  avatar_url: null,
  phone: '+57 300 123 4567',
  bio: 'Apasionada por la moda sostenible.',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const DEMO_SELLER2: Profile = {
  id: 'seller2',
  email: 'moda@revibe.co',
  full_name: 'Camila Torres',
  city: 'Bogotá',
  role: 'seller',
  avatar_url: null,
  phone: '+57 311 987 6543',
  bio: 'Curadora de outfits únicos.',
  created_at: '2024-02-01T00:00:00Z',
  updated_at: '2024-02-01T00:00:00Z',
};

export const DEMO_GARMENTS: Garment[] = [
  {
    id: '1',
    seller_id: 'seller1',
    title: 'Blusa de seda vintage',
    description: 'Hermosa blusa de seda con estampado floral. Perfecta para ocasiones especiales. Tela suave y delicada, corte fluido que favorece todas las figuras.',
    brand: 'Zara',
    size: 'S',
    condition: 'como_nuevo',
    price: 85000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: 'S',
    vibe: 'Vintage',
    category_id: 1,
    created_at: '2025-05-10T10:00:00Z',
    updated_at: '2025-05-10T10:00:00Z',
    seller: DEMO_SELLER,
    category: { id: 1, gender: 'mujer', name: 'Prendas Superiores', slug: 'mujer-superiores' },
  },
  {
    id: '2',
    seller_id: 'seller2',
    title: 'Blazer negro estructurado',
    description: 'Blazer clásico negro con botones dorados. Ideal para looks profesionales o casuales. Excelente calidad de tela, prácticamente nuevo.',
    brand: 'Mango',
    size: 'M',
    condition: 'como_nuevo',
    price: 175000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: 'M',
    vibe: 'Old Money',
    category_id: 1,
    created_at: '2025-05-09T10:00:00Z',
    updated_at: '2025-05-09T10:00:00Z',
    seller: DEMO_SELLER2,
    category: { id: 1, gender: 'mujer', name: 'Prendas Superiores', slug: 'mujer-superiores' },
  },
  {
    id: '3',
    seller_id: 'seller1',
    title: 'Jeans de tiro alto mom fit',
    description: 'Jeans de tiro alto estilo mom fit en azul medio. Cintura elástica cómoda. Versátiles para cualquier ocasión.',
    brand: "Levi's",
    size: '38',
    condition: 'buen_estado',
    price: 120000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: '38',
    vibe: 'Casual',
    category_id: 2,
    created_at: '2025-05-08T10:00:00Z',
    updated_at: '2025-05-08T10:00:00Z',
    seller: DEMO_SELLER,
    category: { id: 2, gender: 'mujer', name: 'Prendas Inferiores', slug: 'mujer-inferiores' },
  },
  {
    id: '4',
    seller_id: 'seller2',
    title: 'Vestido midi floral bohemio',
    description: 'Vestido midi con estampado floral en tonos tierra. Tela liviana perfecta para el calor. Con tirantes ajustables y bolsillos laterales.',
    brand: 'Stradivarius',
    size: 'S',
    condition: 'nuevo_con_etiqueta',
    price: 95000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: 'S',
    vibe: 'Vintage',
    category_id: 3,
    created_at: '2025-05-07T10:00:00Z',
    updated_at: '2025-05-07T10:00:00Z',
    seller: DEMO_SELLER2,
    category: { id: 3, gender: 'mujer', name: 'Vestidos y Conjuntos', slug: 'mujer-vestidos' },
  },
  {
    id: '5',
    seller_id: 'seller1',
    title: 'Camisa Oxford de rayas',
    description: 'Camisa Oxford clásica de rayas azul y blanco. Corte regular, 100% algodón. Perfecta para el trabajo o una salida casual.',
    brand: 'Tommy Hilfiger',
    size: 'M',
    condition: 'buen_estado',
    price: 90000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1588359348347-9bc6cbbb689e?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: 'M',
    vibe: 'Old Money',
    category_id: 4,
    created_at: '2025-05-06T10:00:00Z',
    updated_at: '2025-05-06T10:00:00Z',
    seller: DEMO_SELLER,
    category: { id: 4, gender: 'hombre', name: 'Prendas Superiores', slug: 'hombre-superiores' },
  },
  {
    id: '6',
    seller_id: 'seller2',
    title: 'Chaqueta denim vintage',
    description: 'Chaqueta de jean azul oscuro con detalles desgastados. Un clásico atemporal que combina con todo.',
    brand: 'Pull&Bear',
    size: 'L',
    condition: 'buen_estado',
    price: 110000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: 'L',
    vibe: 'Streetwear',
    category_id: 4,
    created_at: '2025-05-05T10:00:00Z',
    updated_at: '2025-05-05T10:00:00Z',
    seller: DEMO_SELLER2,
    category: { id: 4, gender: 'hombre', name: 'Prendas Superiores', slug: 'hombre-superiores' },
  },
  {
    id: '7',
    seller_id: 'seller1',
    title: 'Pantalón chino beige',
    description: 'Pantalón chino de tela liviana en color beige. Corte slim, cintura media. Perfecto para un look smart casual.',
    brand: 'Arturo Calle',
    size: '40',
    condition: 'como_nuevo',
    price: 75000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: '40',
    vibe: 'Minimalista',
    category_id: 5,
    created_at: '2025-05-04T10:00:00Z',
    updated_at: '2025-05-04T10:00:00Z',
    seller: DEMO_SELLER,
    category: { id: 5, gender: 'hombre', name: 'Prendas Inferiores', slug: 'hombre-inferiores' },
  },
  {
    id: '8',
    seller_id: 'seller2',
    title: 'Bolso de cuero café',
    description: 'Bolso tote de cuero genuino en color café. Amplio, con bolsillos internos organizadores. Correa ajustable.',
    brand: 'Vélez',
    size: 'Único',
    condition: 'buen_estado',
    price: 280000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: null,
    vibe: 'Old Money',
    category_id: 6,
    created_at: '2025-05-03T10:00:00Z',
    updated_at: '2025-05-03T10:00:00Z',
    seller: DEMO_SELLER2,
    category: { id: 6, gender: 'unisex', name: 'Accesorios', slug: 'accesorios' },
  },
  {
    id: '9',
    seller_id: 'seller1',
    title: 'Sudadera oversize gris',
    description: 'Sudadera oversize en gris con diseño minimalista. Tela gruesa tipo felpa. Ideal para días fríos o trabajar desde casa.',
    brand: 'Nike',
    size: 'L',
    condition: 'buen_estado',
    price: 135000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: 'L',
    vibe: 'Streetwear',
    category_id: 4,
    created_at: '2025-05-02T10:00:00Z',
    updated_at: '2025-05-02T10:00:00Z',
    seller: DEMO_SELLER,
    category: { id: 4, gender: 'hombre', name: 'Prendas Superiores', slug: 'hombre-superiores' },
  },
  {
    id: '10',
    seller_id: 'seller2',
    title: 'Falda plisada midi',
    description: 'Falda plisada de tela satinada en color vino. Tiro alto, cintura elástica. Perfecta para eventos o salidas nocturnas.',
    brand: 'Bershka',
    size: 'M',
    condition: 'nuevo_con_etiqueta',
    price: 65000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: 'M',
    vibe: 'Minimalista',
    category_id: 2,
    created_at: '2025-05-01T10:00:00Z',
    updated_at: '2025-05-01T10:00:00Z',
    seller: DEMO_SELLER2,
    category: { id: 2, gender: 'mujer', name: 'Prendas Inferiores', slug: 'mujer-inferiores' },
  },
  {
    id: '11',
    seller_id: 'seller1',
    title: 'Zapatos Oxford negros',
    description: 'Zapatos Oxford de cuero negro con suela de goma. Clásicos y cómodos para el día a día. Poco uso.',
    brand: 'Koaj',
    size: '40',
    condition: 'buen_estado',
    price: 160000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1560343776-97da3f4ea4e7?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: '40',
    vibe: 'Old Money',
    category_id: 6,
    created_at: '2025-04-30T10:00:00Z',
    updated_at: '2025-04-30T10:00:00Z',
    seller: DEMO_SELLER,
    category: { id: 6, gender: 'unisex', name: 'Accesorios', slug: 'accesorios' },
  },
  {
    id: '12',
    seller_id: 'seller2',
    title: 'Abrigo de lana camel',
    description: 'Abrigo largo de lana en tono camel. Corte recto, cierre de botones. El básico del invierno que nunca pasa de moda.',
    brand: 'Zara',
    size: 'S',
    condition: 'como_nuevo',
    price: 350000,
    status: 'disponible',
    images: ['https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=600&h=800&q=80'],
    images_processed: true,
    ai_suggested_size: 'S',
    vibe: 'Old Money',
    category_id: 1,
    created_at: '2025-04-29T10:00:00Z',
    updated_at: '2025-04-29T10:00:00Z',
    seller: DEMO_SELLER2,
    category: { id: 1, gender: 'mujer', name: 'Prendas Superiores', slug: 'mujer-superiores' },
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-001',
    buyer_id: 'buyer1',
    seller_id: 'seller1',
    garment_id: '1',
    total_amount: 85000,
    status: 'entregada',
    shipping_address: {
      full_name: 'Ana García',
      phone: '+57 312 345 6789',
      address: 'Cra 15 #82-50 Apto 301',
      city: 'Bogotá',
      neighborhood: 'Chapinero',
    },
    notes: null,
    created_at: '2025-05-01T10:00:00Z',
    updated_at: '2025-05-05T10:00:00Z',
    garment: DEMO_GARMENTS[0],
    buyer: {
      id: 'buyer1',
      email: 'ana@gmail.com',
      full_name: 'Ana García',
      city: 'Bogotá',
      role: 'buyer',
      avatar_url: null,
      phone: '+57 312 345 6789',
      bio: null,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    seller: DEMO_SELLER,
  },
  {
    id: 'ord-002',
    buyer_id: 'buyer2',
    seller_id: 'seller2',
    garment_id: '4',
    total_amount: 95000,
    status: 'enviada',
    shipping_address: {
      full_name: 'María Jiménez',
      phone: '+57 301 234 5678',
      address: 'Cll 10 #43A-20',
      city: 'Medellín',
      neighborhood: 'El Poblado',
    },
    notes: null,
    created_at: '2025-05-05T10:00:00Z',
    updated_at: '2025-05-06T10:00:00Z',
    garment: DEMO_GARMENTS[3],
    buyer: {
      id: 'buyer2',
      email: 'maria@gmail.com',
      full_name: 'María Jiménez',
      city: 'Medellín',
      role: 'buyer',
      avatar_url: null,
      phone: '+57 301 234 5678',
      bio: null,
      created_at: '2024-02-01T00:00:00Z',
      updated_at: '2024-02-01T00:00:00Z',
    },
    seller: DEMO_SELLER2,
  },
  {
    id: 'ord-003',
    buyer_id: 'buyer1',
    seller_id: 'seller1',
    garment_id: '5',
    total_amount: 90000,
    status: 'confirmada',
    shipping_address: {
      full_name: 'Ana García',
      phone: '+57 312 345 6789',
      address: 'Cra 15 #82-50 Apto 301',
      city: 'Bogotá',
      neighborhood: 'Chapinero',
    },
    notes: 'Por favor empacar bien',
    created_at: '2025-05-10T10:00:00Z',
    updated_at: '2025-05-10T10:00:00Z',
    garment: DEMO_GARMENTS[4],
    buyer: {
      id: 'buyer1',
      email: 'ana@gmail.com',
      full_name: 'Ana García',
      city: 'Bogotá',
      role: 'buyer',
      avatar_url: null,
      phone: '+57 312 345 6789',
      bio: null,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    seller: DEMO_SELLER,
  },
];
